const districts = [
    { name: "Ariyalur", touristPlaces: ["Udayamarthandapuram Bird Sanctuary", "Thirumanimutharu Dam", "Melpadi Kovil", "Sri Ekambareswarar Temple", "Neyveli Lignite Corporation", "Kamalapuram", "Perambalur"], imageUrl: "https://imgs.search.brave.com/ZX6cV-QXFkLSU9Q8eNGdDBcmayz8R1SSOUl8vKS9bvk/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvY29tbW9ucy84LzhjL0FyaXlhbHVyX1JhaWx3YXlfU3RhdGlvbi5qcGc" },
    { name: "Chengalpattu", touristPlaces: ["Mahabalipuram", "Vedanthangal Bird Sanctuary", "Kovalam Beach", "Thirukazhukundram", "Tirumukkudal", "Tiruporur", "Chengalpattu"], imageUrl: "https://imgs.search.brave.com/XdOrdyKhXjeNWOA3LGwoYqVhNLN8XvDMFg_vGPJDpCo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/czN3YWFzLmdvdi5p/bi9zMzk3NzhkNWQy/MTljNTA4MGI5YTZh/MTdiZWYwMjkzMzFj/L3VwbG9hZHMvMjAy/MS8wNi8yMDIxMDYz/MDQwLmpwZw" },
    { name: "Chennai", touristPlaces: ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "Government Museum, Chennai", "Arignar Anna Zoological Park", "Santhome Basilica", "Guindy National Park"], imageUrl: "https://imgs.search.brave.com/I10NOarsF3wlUpj8qmbZzLB9StMsh4s4MIuMHlVZXz0/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTIx/MTk1MjkyOS9waG90/by9tYXJpbmEtYmVh/Y2gtY2hlbm5haS1j/aXR5LXRhbWlsLW5h/ZHUtaW5kaWEtYmF5/LW9mLWJlbmdhbC1j/aGVubmFpLXRvdXJp/c20tZWFzdC1jb2Fz/dC1yb2FkLndlYnA_/Yj0xJnM9MTcwNjY3/YSZ3PTAmaz0yMCZj/PUFMSF9hWUgtQzla/cHo5eVdjdHZ2QU0w/ZS12RHRuZ3M1XzR2/MnExT0RvV0k9" },
    { name: "Coimbatore", touristPlaces: ["Ooty", "Coonoor", "Siruvani Waterfalls", "Kovai Kutralam Falls", "Dhyanalinga", "Monkey Falls", "Black Thunder Water Theme Park"], imageUrl: "https://imgs.search.brave.com/eUKZmf_bhRdBFKWsrjh9HfLtudXsoymlD7tZdptqfnc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNTIw/MTI0MzEwL3Bob3Rv/L2NvaW1iYXRvcmUt/bWFya2VkLW9uLW1h/cC13aXRoLXJlZC1w/dXNocGluLmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz1zLUdE/SU8xVUhqZzVaTDRP/QUFjSHJfNjhBUE5t/SzB5ek9pWXVzVVJx/SWFnPQ" },
    { name: "Cuddalore", touristPlaces: ["Silver Beach", "Pichavaram Mangrove Forest", "Padaleeswarar Temple", "Devanampattinam Beach", "Paradise Beach", "Kurinjipadi", "Chidambaram"], imageUrl: "https://imgs.search.brave.com/7y36o4hiKa65UMnw3aL9iQDRuuADR6Q-2zv6T7h3PTA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy82/LzY2L1NpbHZlcl9C/ZWFjaF9waG90by5q/cGc" },
    { name: "Dharmapuri", touristPlaces: ["Hogenakkal Falls", "Krishnagiri Dam", "Theerthamalai Temple", "Hanumanthathirtham", "Chinnar Dam", "Subramanya Siva Memorial Pillar", "Hosur"], imageUrl: "https://imgs.search.brave.com/80Je_Nt8ERMWZ5M2Cl0zeUyrcKaJtOMdSVDxNhrl6AU/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbnN0/YWdyYW0uZmJkbjEu/bmV0L3ZwL2h0X21l/ZGlhLzI5MDk1Mzc2/MzA0NjM3MDAxNi8y/NTI2NTE3MTI4OTM1/OTgwOTAvNzAwMDE0/MTU5Nzk4NTU5MjI5/NTY1NDc4OTAzMDk3/OTQ4NDE4OTUxODg0/OTQzNTM0MTM5MTAw/NDE4NjEwMjg5MzEw/L2Q2YTVlYzAwZDMu/anBnP2V4aWZ0PWpw/ZWc" },
    { name: "Dindigul", touristPlaces: ["Kodaikanal", "Berijam Lake", "Palani Murugan Temple", "Silver Cascade Falls", "Pillar Rocks", "Dindigul Fort", "Thalaiyar Falls"], imageUrl: "https://imgs.search.brave.com/RgsumMwVfqXqxkKLMdOtD7Zb2ftCvL56gJ_pL_UmtnI/rs:fit:1200:1080:1/g:ce/aHR0cHM6Ly93d3cu/c2F0aXNjYWxlcmVz/b3J0cy5jb20vd3At/Y29udGVudC91cGxv/YWRzLzIwMjAvMTAv/S2lzc2V2aWR5YS1U/aGFsYWl5YXItV2F0/ZXJmYWxsLW9yLU1h/Z2dpZS1GYWxscy1P/dHRlci5qcGc" },
    { name: "Erode", touristPlaces: ["Bannari Amman Temple", "Vellode Bird Sanctuary", "Bhavani", "Perumpallam Dam", "Chennimalai", "Kodiveri Dam", "Sathyamangalam Wildlife Sanctuary"], imageUrl: "https://imgs.search.brave.com/bvfyVCYoFvqaP1a38HDTGbfywmkJ8v5wGRDTwepBCxA/rs:fit:1200:1080:1/g:ce/aHR0cHM6Ly9jb2xv/bmljYW1hZ3ppbmVz/LmNvbS93cC1jb250/ZW50L3VwbG9hZHMv/MjAyMC8wOC9QYXJr/LUNvbm5lci1FY2hv/LVRvdXJzLVNhdGhp/eS1Gb3Jlc3QtU2Vx/dW9pYS1QYXJrIFNp/dHR1YXRlZC1pbi1N/YWlubWFsLVRhbWls/LU5hZHUvRXJvZGUt/SW5kaWEtRmVhdHVy/ZWQtSXMuanBn" },
    { name: "Kallakurichi", touristPlaces: ["Kalvarayan Hills", "Siruvanthadu Falls", "Kachirayapalayam", "Ramanatham", "Ulundurpettai", "Vellimalai", "Veeracholapuram"], imageUrl: "https://imgs.search.brave.com/zpT8TQwsDiSWXEiwz7bWm7AeG_XSQ5Z0n-VoDpVCmSg/rs:fit:1100:1080:1/g:ce/aHR0cHM6Ly9hLXN0/dWRpby5jby93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyMC8wOC9E/aXN0YW50LXZpZXctb2Yta2FsbGFrdXJpY2hpLWZyb20tcmFqYXRoYW5zLmpwZw" },
    { name: "Kanchipuram", touristPlaces: ["Ekambareswarar Temple", "Kamakshi Amman Temple", "Kailasanathar Temple", "Varadaraja Perumal Temple", "Kanchi Kudil", "Vedanthangal Bird Sanctuary", "Kanchi Kamakoti Peetam"], imageUrl: "https://imgs.search.brave.com/30fHME4qe5Ldw0umbaFWm8ykYf9GMIk-GQaO-nY1CRo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNDcz/NDYyNzMyL3Bob3Rv/L2thbmNoaXB1cmFt/LWluZGlhLWxvYWRp/bmctc2lsay10aHJl/YWQtaW50by1oYW5k/LWxvb20uanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPW5QRzB1/OTFubXota1Z3RDBn/UW5DUUxGYjhhX19j/Vk1FRnpVeVZxQXB2/OTg9" },
    { name: "Kanyakumari", touristPlaces: ["Vivekananda Rock Memorial", "Kanyakumari Beach", "Thiruvalluvar Statue", "Padmanabhapuram Palace", "Mathur Hanging Bridge", "Vattakottai Fort", "Muttom Beach"], imageUrl: "https://imgs.search.brave.com/ar1gxnPrjWVP_DfR8MGv13kA3qFb_peqxSK_tfUHxPw/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFtaWxuYWR1dG91/cmlzbS50bi5nb3Yu/aW4vaW1nL3BhZ2Vz/L21vYmlsZS90aGly/dXZhbGx1dmFyLXN0/YXR1ZS1rYW55YWt1/bWFyaS0xNjU1MTk2/NjU5XzVhNTA1MGJj/YjQ3ZmVhOTdhMDI1/LndlYnA" },
    { name: "Karur", touristPlaces: ["Nerur Shiva Temple", "Pugalur Dam", "Mayanur", "Vennandur", "Kulithalai", "Krishnarayapuram", "Aravakurichi"], imageUrl: "https://imgs.search.brave.com/fo-llkYz2GC532SISZXBsbU2fJd2YlCg6r8WaGIQc-c/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy80/LzRjL0thcnVyY2l0/eTIuanBn" },
    { name: "Krishnagiri", touristPlaces: ["Krishnagiri Dam", "Rayakottah", "Kelavarapalli Reservoir", "Bears Hill", "Parvathamalai", "Sri Ranganathar Swamy Temple", "Hosur"], imageUrl: "https://imgs.search.brave.com/Tqr5pFIJsCl6TLl7Pi_i8NsVKvZM0JxKMkSG38sAazI/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9k/L2Q2L0tyaXNoYW5n/aXJpX0RhbV9PdXRz/aWRlLmpwZw" },
    { name: "Madurai", touristPlaces: ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace", "Gandhi Memorial Museum", "Vaigai Dam", "Thirupparamkunram Murugan Temple", "Alagar Koyil", "Vandiyur Mariamman Teppakulam"], imageUrl: "https://imgs.search.brave.com/bwvgs-uoRtJHgw08qaWLSKVjDCqJOoXJSef_c34xKuM/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9oaW5k/dS10ZW1wbGUtdG93/ZXItdGFuay0xNDE4/MTcxMy5qcGc" },
    { name: "Nagapattinam", touristPlaces: ["Velankanni Church", "Nagore Dargah", "Poompuhar Beach", "Karaikal Beach", "Mayiladuthurai", "Sikkal", "Tharangambadi"], imageUrl: "https://imgs.search.brave.com/OhqLBUW81uW1ZJ5Ig7Hk_4HgCl5nFzpaGkhowHDlGLI/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9j/L2M3L05hZ2FwYXR0/aW5hbDIuSlBH" },
    { name: "Namakkal", touristPlaces: ["Namakkal Fort", "Kolli Hills", "Arappaleeswarar Temple", "Namakkal Rock Fort", "Tiruchengode", "Mohanur", "Paramathi-Velur"], imageUrl: "https://imgs.search.brave.com/ljMHWArexSyElhxG4zPbEvvS-zwRxqgSu4gEnLzoiTY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy84/LzhkL0tvbGxpX0hp/bGxzX1dhdGVyZmFs/bHMuSlBH" },
    { name: "Nilgiris", touristPlaces: ["Ooty", "Coonoor", "Doddabetta Peak", "Pykara Falls", "Botanical Gardens", "Tea Museum", "Avalanche Lake"], imageUrl: "https://imgs.search.brave.com/QVHd0svXKmw4vi5RCk_Cufc3oiFKbq5SaHRfzTip6ck/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFtaWxuYWR1dG91/cmlzbS50bi5nb3Yu/aW4vaW1nL3BhZ2Vz/L21vYmlsZS9uaWxn/aXJpcy0xNjU3NDYz/MzAwX2E1YzFlNTNh/YzUyOGI3YjA3ZmQw/LndlYnA" },
    { name: "Perambalur", touristPlaces: ["Siruvachur Mathura Kaliamman Temple", "Elakurichi", "Thirumandangudi", "Thirumanur", "Alathur", "Veppanthattai", "Vengambakkam"], imageUrl: "https://imgs.search.brave.com/DBjasRKFtok1pBGglnO0iEijbPaApLH0cKAPfqRvFpA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MWEvMTUvYWYvMTAv/Y2FwdGlvbi5qcGc" },
    { name: "Pudukkottai", touristPlaces: ["Brihadeeswarar Temple", "Sittanavasal", "Kodumbalur", "Thirumayam Fort", "Kunnandarkoil Cave Temple", "Vettanur", "Thirugokarnam"], imageUrl: "https://imgs.search.brave.com/6dYH3FZI4BOlAgzu1hYKyyqAFdcBQd1nDp1IAxWnvds/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9i/L2IyL1B1ZHVra290/dGFpX0Rpc3RyaWN0/X0NvdXJ0LmpwZw" },
    { name: "Ramanathapuram", touristPlaces: ["Rameswaram", "Dhanushkodi", "Pamban Bridge", "Kurusadai Island", "Uthirakosamangai", "Thiruppullani", "Devipattinam"], imageUrl: "https://imgs.search.brave.com/xYa5PLsVMxn2jcVKldxLvA3sa8KVU5MTPn9j0Dhp1Ng/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFtaWxuYWR1dG91/cmlzbS50bi5nb3Yu/aW4vaW1nL3BhZ2Vz/L21vYmlsZS9yYW1l/c3dhcmFtLTE2NTcw/MDM0NjJfZmIzMzBj/ZDM2MWY3YTdlZmVi/OTgud2VicA" },
    { name: "Ranipet", touristPlaces: ["Mahendravadi", "Jalakandeswarar Temple", "Vallimalai", "Amirthi Zoological Park", "Arcot", "Yelagiri Hills", "Vellore Fort"], imageUrl: "https://imgs.search.brave.com/Y4g0DZSzVxfxej1Qcb_rDKLbKYyMzp0tn13K1RsLIrU/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/czN3YWFzLmdvdi5p/bi9zMzI3MjNkMDky/YjYzODg1ZTBkN2My/NjBjYzAwN2U4Yjlk/L3VwbG9hZHMvYmZp/X3RodW1iLzIwMTkx/MjIwMzAtb2x3N2Ex/MW52MDJzYWd6bzFu/YWE1bmhqM252a2J5/am93NG1sa29iYzJv/LmpwZw" },
    { name: "Salem", touristPlaces: ["Yercaud", "Kailasanathar Temple", "Mettur Dam", "Sankagiri Fort", "Kurumbapatti Zoological Park", "1008 Lingam Temple", "Sri Veeraganapathy Temple"], imageUrl: "https://imgs.search.brave.com/By8qbY_1pACTMmILwhIqEjocdp8Kn_SbeAFVz-Kt4q8/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy80/LzQyL1NhbGVtX1Nl/ZWxhbmFpY2tlbnBh/dGkuanBn" },
    { name: "Sivagangai", touristPlaces: ["Karaikudi", "Chettinad Palace", "Manora Fort", "Kundrakudi Murugan Temple", "Pillayarpatti Karpaga Vinayagar Temple", "Kollangudi", "Tirupathur"], imageUrl: "https://imgs.search.brave.com/CMrt1e0eUqKZ0t9YeVKdresCDPUEQkRmUY6wxHwRKsg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy85/LzlhL1NpdmFnYW5n/YWlfcmFpbHdheV9z/dGF0aW9uLmpwZw" },
    { name: "Tenkasi", touristPlaces: ["Courtallam Falls", "Tenkasi Hill Temple", "Papanasam Dam", "Manjolai Hills", "Kuttralam", "Kasi Viswanathar Temple", "Thenmalai"], imageUrl: "https://imgs.search.brave.com/3DAfhTns-9t6TrV-7TVbFI189yeOJFxwSTXiIBu723E/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9m/L2Y3L1RoZV9tYWdu/aWZpY2VudF9LYXNp/X1Zpc2h3YW5hdGhh/dF9UZW1wbGVfUmFq/YWdvcHVyYW0uanBn" },
    { name: "Thanjavur", touristPlaces: ["Brihadeeswarar Temple", "Thanjavur Palace", "Thiruvaiyaru", "Thirukandiyur", "Swamimalai", "Kumbakonam", "Darasuram"], imageUrl: "https://imgs.search.brave.com/C0AkWyDpWd3OIOCbnFQOPLD_4lts27J_TzPTi0_rVfk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/dGFtaWxuYWR1dG91/cmlzbS50bi5nb3Yu/aW4vaW1nL3BhZ2Vz/L21vYmlsZS90aGFu/amF2dXItMTY1NDc3/MDUyMV8xOTkyYzQ5/ZmFhZWFiY2NhYzFk/Ny53ZWJw" },
    { name: "Theni", touristPlaces: ["Suruli Falls", "Kumbakkarai Falls", "Meghamalai", "Thekkady", "Vaigai Dam", "Periyar Wildlife Sanctuary", "Kailasanathar Temple"], imageUrl: "https://imgs.search.brave.com/Cf_WcJc1v294Cas1l4zq4ihLHHzaYcHCIv8tRpby1U4/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy85/LzljL01hbmphbGFy/dV9EYW0sX1RoZW5p/X0Rpc3RyaWN0Lmpw/Zw" },
    { name: "Thoothukudi", touristPlaces: ["Tuticorin Beach", "Hare Island", "Our Lady of Snows Basilica", "Manapad Beach", "Vattakottai Fort", "Panchalankurichi Fort", "Kalakkadu Sanctuary"], imageUrl: "https://imgs.search.brave.com/O6AlgGkHz-6geJBw4m8IqAVXA_H6nlcp0PX5HOVvBgA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy85/LzkzL01hcmFra2Fu/YV9TYWx0X1BhbnMu/SlBH" },
    { name: "Tiruchirappalli", touristPlaces: ["Rockfort Temple", "Srirangam Temple", "Kallanai Dam", "St. Joseph's Church", "Tiruvanaikkaval", "Viralimalai Murugan Temple", "Puliyancholai Falls"], imageUrl: "https://imgs.search.brave.com/JkR3IQJKjPcbV-1ZBUY9pnZ88Ted-ZoBZ-tQ29-CECA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNTE2/MDA4NDQzL3Bob3Rv/L3N1bnJpc2UtYXQt/dHJpY2h5LmpwZz9z/PTYxMng2MTImdz0w/Jms9MjAmYz1DUEk1/TXhsYXYxY0tOVXRX/ZkY5RWE1VlFuMFRn/R0hPdGpxQnhfcUl4/YWpRPQ" },
    { name: "Tirunelveli", touristPlaces: ["Nellaiappar Temple", "Thamirabarani River", "Manimuthar Falls", "Kanyakumari", "Vivekananda Rock Memorial", "Thirupudaimaruthur", "Courtallam"], imageUrl: "https://imgs.search.brave.com/30DqmOswmlKsNLLEa96FZ7tMTY4dyepjBVTZ4xeM8Ec/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDQvMmYvOTUvZWUv/Y291dHJhbGxhbS13/YXRlci1mYWxscy5q/cGc" },
    { name: "Tiruppur", touristPlaces: ["Noyyal River", "Tiruppur Kumaran Memorial Statue", "Avinashiappar Temple", "Amaravathi Dam", "Thirumoorthy Hills", "Koolipalayam", "Orathuppalayam Dam"], imageUrl: "https://imgs.search.brave.com/GYzPK6T7DzPqA-NHTJINeMY7BEZkHUp0uxAN4h_dxug/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbS5o/dW50LmluL2NnL1Rp/cnVwdXIvQ2l0eS1H/dWlkZS90aXJ1cHB1/ci5KUEc" },
    { name: "Tiruvallur", touristPlaces: ["Vadapalani Murugan Temple", "Vandalur Zoo", "Tiruvallur Veeraraghava Temple", "Sri Kandaswamy Temple", "Sholingur Narasimha Swamy Hill", "Pulicat Lake", "Melmaruvathur"], imageUrl: "https://imgs.search.brave.com/8-oH4jEqgo-5fg-pw-9STtAlMXC-giP5PR7G0EeYJl0/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9m/L2Y0L1N0YXR1ZV9v/Zl9UaGlydXZhbGx1/dmFyLmpwZw" },
    { name: "Tiruvannamalai", touristPlaces: ["Arunachaleswarar Temple", "Sathanur Dam", "Virupaksha Cave", "Ramana Ashram", "Virupaksha Cave", "Skandashram", "Sri Ramana Maharshi Ashram"], imageUrl: "https://imgs.search.brave.com/Da7u63vLyoGQfSUkUv2Vt7_mYRshz9R-EK2J2pkAY3w/rs:fit:860:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy9h/L2FhL1RoaXJ1dmFu/bmFtYWxhaSxfQXJ1/bmFjaGFsZXN2YXJh/X1RlbXBsZSxfQW5u/YW1hbGFpeWFyX1Rl/bXBsZSxfUGFub3Jh/bWljX3ZpZXcsX0lu/ZGlhLmpwZw" }
];

document.addEventListener('DOMContentLoaded', () => {
    const destinationInput = document.getElementById('destinationInput');
    const autocompleteList = document.getElementById('autocomplete-list');
    const resultsDiv = document.getElementById('results');

    destinationInput.addEventListener('input', function() {
        const query = this.value.toLowerCase();
        autocompleteList.innerHTML = '';

        if (query) {
            const matchingDistricts = districts.filter(district =>
                district.name.toLowerCase().includes(query)
            );

            matchingDistricts.forEach(district => {
                const listItem = document.createElement('div');
                listItem.classList.add('autocomplete-item');
                listItem.textContent = district.name;
                listItem.addEventListener('click', function() {
                    destinationInput.value = district.name;
                    displayResults(district);
                    autocompleteList.innerHTML = '';
                });
                autocompleteList.appendChild(listItem);
            });
        }
    });

    function displayResults(district) {
        resultsDiv.innerHTML = `
            <h2>${district.name}</h2>
            <img src="${district.imageUrl}" alt="Image of ${district.name}">
            <h3>Tourist Places:</h3>
            <ul>
                ${district.touristPlaces.map(place => `<li>${place}</li>`).join('')}
            </ul>
        `;
    }
});